name: Docker Publish

on:
  push:
    branches:
      - netease_api_proxy  # 或者您使用的其他分支名

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get the current branch
        id: get-branch
        run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check for changes in folders and build images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          CURRENT_BRANCH=${{ steps.get-branch.outputs.branch }}
          echo "Current branch: $CURRENT_BRANCH"
          
          PREV_SHA=$(git rev-parse HEAD~1)
          CURRENT_SHA=$(git rev-parse HEAD)
          echo "Previous SHA: $PREV_SHA"
          echo "Current SHA: $CURRENT_SHA"
          
          DIFF_OUTPUT=$(git diff --name-only $PREV_SHA $CURRENT_SHA)
          echo "Diff output: $DIFF_OUTPUT"
          
          GO_MOD_CHANGED=false
          if echo "$DIFF_OUTPUT" | grep -q '^go\.mod$'; then
            echo "go.mod has changed."
            GO_MOD_CHANGED=true
          fi
          
          FOLDERS=$(echo "$DIFF_OUTPUT" | grep -Eo '^[a-zA-Z0-9_-]+/' | sort -u | sed 's/\/$//')
          echo "Folders with changes: $FOLDERS"
          
          for folder in $FOLDERS; do
            if [ "$GO_MOD_CHANGED" = true ] || echo "$DIFF_OUTPUT" | grep -q "^${folder}/"; then
              echo "Building and pushing image for folder: $folder on branch $CURRENT_BRANCH"
              docker build -t $DOCKER_USERNAME/sk5_${folder}:${CURRENT_BRANCH} --build-arg APP_DIR=${folder} .
              docker push $DOCKER_USERNAME/sk5_${folder}:${CURRENT_BRANCH}
            fi
          done
 

