name: Docker Publish

on:
  push:
    branches:
      - main  # 或者您使用的其他分支名

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check for changes in folders and build images
        run: |
          PREV_SHA=$(git rev-parse HEAD~1)
          CURRENT_SHA=$(git rev-parse HEAD)
          echo "Previous SHA: $PREV_SHA"
          echo "Current SHA: $CURRENT_SHA"
          
          DIFF_OUTPUT=$(git diff --name-only $PREV_SHA $CURRENT_SHA)
          echo "Diff output: $DIFF_OUTPUT"
          
          FOLDERS=$(echo "$DIFF_OUTPUT" | grep -Eo '^[a-zA-Z0-9_-]+/' | sort -u | sed 's/\/$//')
          echo "Folders with changes: $FOLDERS"
          
          for folder in $FOLDERS; do
            echo "Building and pushing image for folder: $folder"
            docker build -t ***/sk5_${folder}:latest --build-arg APP_DIR=${folder} .
            docker push ***/sk5_${folder}:latest
          done

