name: Docker Publish

on:
  push:
    branches:
      - main  # 或者您使用的其他分支名

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check for changes in folders and build images
        run: |
          FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/$' | sed 's/\/$//')
          for folder in $FOLDERS; do
            echo "Building and pushing image for folder: $folder"
            docker build -t 23233/sk5_${folder}:latest --build-arg APP_DIR=${folder} .
            docker push 23233/sk5_${folder}:latest
          done