name: Docker Publish

on:
  push:
    branches:
      - main  # 或者您使用的其他分支名

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push control image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 23233/sk5_control:latest
          build-args: |
            APP_DIR=control

      - name: Build and push terminal image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 23233/sk5_terminal:latest
          build-args: |
            APP_DIR=terminal
